import { postUi } from './postStyles'
import { reviewDialogClasses, reviewUi } from './reviewStyles'

const iconButton = 'inline-flex h-[32px] w-[32px] shrink-0 items-center justify-center rounded-[6px] border border-transparent bg-transparent p-0 text-[#8494a8] cursor-pointer hover:bg-[#edf4fb] hover:text-[#1a528e] focus-visible:outline-3 focus-visible:outline-solid focus-visible:outline-offset-3 focus-visible:outline-[#60a5fa] disabled:cursor-not-allowed disabled:opacity-45'
const compactIconButton = `${iconButton} h-[28px] w-[28px]`

export const escalationUi = {
  root: 'box-border px-[32px] py-[28px] text-[13px] text-[#16233a] [&_*]:box-border [&_button]:[font-family:inherit] max-[1200px]:px-[22px] max-[600px]:px-[16px] max-[600px]:py-[22px]',
  stats: 'mb-[24px] grid grid-cols-3 gap-[16px] max-[900px]:grid-cols-1 max-[600px]:gap-[10px]',
  stat: 'flex items-start gap-[14px] rounded-[11px] border border-solid border-[#dce4ed] bg-white p-[20px] text-left transition-colors hover:border-[#9bbce0] max-[1200px]:gap-[10px] max-[1200px]:p-[15px] max-[600px]:items-center max-[600px]:p-[14px]',
  statIcon: 'flex shrink-0 rounded-[10px] bg-[#fff4da] p-[10px] text-[#a46105] max-[1200px]:p-[7px]',
  statOverdue: 'bg-[#e6f0fa] text-[#1a528e]',
  statResolved: 'bg-[#dff7ed] text-[#078361]',
  statLabel: 'block text-[12px] font-semibold text-[#43536b]',
  statValue: 'mt-[8px] mb-[6px] block text-[28px] font-bold leading-[1.3] text-[#16233a]',
  statDescription: 'block text-[10px] leading-[1.6] text-[#738298]',
  tabs: 'mb-[20px] flex flex-wrap gap-[6px] border-0 border-b border-solid border-[#dce4ed]',
  tab: 'inline-flex items-center gap-[8px] border-0 border-b-2 border-solid border-transparent bg-transparent px-[15px] py-[12px] text-[12px] font-semibold text-[#738298] cursor-pointer hover:text-[#1a528e]',
  tabActive: '!border-[#1a528e] !text-[#1a528e]',
  tabCount: 'rounded-[5px] bg-[#e4ebf3] px-[6px] py-[2px] text-[10px] text-[#496786]',
  filterSection: 'rounded-[12px] border border-solid border-[#dce4ed] bg-white p-[22px] shadow-[0_2px_6px_#16233a03] max-[600px]:p-[16px]',
  filterGrid: 'grid grid-cols-[1.5fr_1.2fr_1fr_1fr_auto] items-end gap-[14px] max-[1200px]:grid-cols-2 max-[600px]:grid-cols-1',
  label: 'flex min-w-0 flex-col gap-[5px] text-[13px] font-semibold text-[#43536b]',
  input: `${reviewUi.input} text-[13px]`,
  resetButton: postUi.resetButton,
  summary: reviewUi.summary,
  notice: reviewUi.notice,
  pagination: reviewUi.pagination,
  pageButton: reviewUi.pageButton,
  selectedPage: reviewUi.selectedPage,
  tableContainer: 'overflow-x-hidden overflow-y-visible rounded-[11px] border border-solid border-[#aebfd1] bg-white shadow-[0_2px_7px_#16233a0a]',
  table: 'w-full min-w-0 table-fixed border-collapse text-left text-[11px]',
  tableHead: 'border-0 border-b border-solid border-[#c2d1e2] bg-[#f8fafc] px-[7px] py-[12px] text-[11px] font-semibold text-[#64748b] [overflow-wrap:anywhere]',
  tableCell: 'border-0 border-b border-solid border-[#d7e1eb] px-[7px] py-[11px] align-middle text-[11px] [overflow-wrap:anywhere]',
  code: 'block mb-[6px] text-left text-[10px] font-semibold whitespace-nowrap text-[#1a528e]',
  title: 'block border-0 bg-transparent p-0 text-left text-[12px] leading-[1.45] font-semibold text-[#16233a] [font-family:inherit] [overflow-wrap:anywhere] cursor-pointer hover:text-[#1a528e]',
  category: 'mt-[6px] flex w-fit max-w-full rounded-[5px] bg-[#f0f3f7] px-[6px] py-[4px] text-[10px] font-semibold text-[#697b91]',
  groupStale: 'mt-[8px] flex w-fit rounded-[5px] bg-[#fff4da] px-[6px] py-[4px] text-[10px] font-semibold text-[#a46105]',
  groupOverdue: 'mt-[8px] flex w-fit rounded-[5px] bg-[#e6f0fa] px-[6px] py-[4px] text-[10px] font-semibold text-[#1a528e]',
  party: 'flex min-w-0 flex-col items-start gap-[3px] [overflow-wrap:anywhere] text-[11px] [&+&]:mt-[10px] [&+&]:border-0 [&+&]:border-t [&+&]:border-solid [&+&]:border-[#edf1f5] [&+&]:pt-[10px]',
  partyLost: 'text-[#c12d4d]',
  partyFound: 'text-[#1a528e]',
  partySide: 'text-[9px] font-bold tracking-[0.3px]',
  partyName: 'text-[11px] font-semibold text-[#334155]',
  partyEmail: 'text-[10px] text-[#738298] [overflow-wrap:anywhere]',
  partyConfirm: 'text-[9px] text-[#8494a8]',
  partyConfirmed: 'text-[#078361]',
  chatOpened: 'inline-flex items-center gap-[5px] text-[11px] text-[#1a528e]',
  chatClosed: 'inline-flex items-center gap-[5px] text-[11px] text-[#8494a8]',
  meeting: 'mt-[8px] mb-0 text-[10px] leading-[1.6] text-[#738298]',
  age: 'block whitespace-nowrap text-[12px] text-[#334155]',
  smallNote: 'mt-[5px] block text-[9px] leading-[1.5] text-[#8494a8]',
  status: 'inline-flex rounded-[5px] px-[7px] py-[4px] text-[10px] font-semibold',
  statusPending: 'bg-[#fff4da] text-[#a46105]',
  statusContacted: 'bg-[#e6f0fa] text-[#1a528e]',
  statusCompleted: 'bg-[#dff7ed] text-[#078361]',
  statusRejected: 'bg-[#fdecef] text-[#bd2a49]',
  statusStack: 'flex flex-col items-start gap-[7px]',
  verified: 'inline-flex items-center gap-[4px] text-[10px] text-[#078361]',
  hidden: 'text-[10px] text-[#c12d4d]',
  actions: 'mx-auto grid w-[106px] grid-cols-3 place-items-center gap-[5px]',
  viewAction: `${iconButton} hover:bg-[#e6f0fa] hover:text-[#1a528e]`,
  successAction: `${iconButton} hover:bg-[#d1fae5] hover:text-[#059669]`,
  dangerAction: `${iconButton} hover:bg-[#fdecef] hover:text-[#d93a5b]`,
  compactViewAction: `${compactIconButton} hover:bg-[#e6f0fa] hover:text-[#1a528e]`,
  compactSuccessAction: `${compactIconButton} hover:bg-[#d1fae5] hover:text-[#059669]`,
  compactDangerAction: `${compactIconButton} hover:bg-[#fdecef] hover:text-[#d93a5b]`,
  parties: 'my-[20px] grid grid-cols-2 gap-[14px] max-[600px]:grid-cols-1',
  partyCard: 'm-0 rounded-[9px] border border-solid border-[#dce4ed] p-[14px]',
  detailTitle: 'mt-[20px] mb-[10px] text-[20px] font-bold leading-[1.5] text-[#1a528e] [overflow-wrap:anywhere]',
  detailList: reviewUi.detailList,
  heading: reviewUi.heading,
  editTitle: reviewUi.editTitle,
  description: reviewUi.description,
  timeline: 'flex flex-col gap-[12px]',
  timelineItem: 'block w-full rounded-[5px] border border-solid border-[#e2e8f0] border-l-[3px] border-l-[#9bbce0] bg-[#f8fafc] px-[12px] py-[12px] text-left',
  timelineAction: 'block text-[12px] font-semibold text-[#1a528e]',
  timelineMeta: 'mt-[5px] mb-[5px] block text-[10px] text-[#738298]',
  timelineReason: 'm-0 text-[11px] leading-[1.7] text-[#43536b] [overflow-wrap:anywhere]',
  logDetail: 'block w-full cursor-pointer border-0 bg-transparent p-0 text-left text-[12px] leading-[1.7] text-[#43536b] [font-family:inherit] [overflow-wrap:anywhere] hover:text-[#1a528e]',
  logLink: 'mt-[5px] flex items-center gap-[4px] text-[10px] text-[#1a528e]',
  explanation: 'mb-[18px] rounded-[8px] bg-[#edf6fd] p-[14px] text-[12px] leading-[1.8] text-[#31597d]',
  form: reviewUi.form,
  checkbox: 'mb-[10px] flex flex-row items-start gap-[10px] text-[12px] leading-[1.7] cursor-pointer',
  targets: 'my-[16px] rounded-[8px] border border-solid border-[#dce4ed] px-[14px] pt-[12px] pb-[4px]',
  targetLegend: 'px-[5px] text-[12px] font-semibold text-[#43536b]',
  error: reviewUi.error,
  hint: reviewUi.hint,
  button: reviewUi.button,
  primaryButton: reviewUi.successButton,
  dangerButton: reviewUi.dangerButton,
}

export const escalationDialogClasses = { ...reviewDialogClasses, button: escalationUi.button }
