const focus = 'focus-visible:outline-3 focus-visible:outline-solid focus-visible:outline-offset-3 focus-visible:outline-[#60a5fa]'
const icon = `inline-flex h-[32px] w-[32px] shrink-0 items-center justify-center rounded-[6px] border border-solid p-0 text-[13px] [font-family:inherit] cursor-pointer disabled:cursor-not-allowed disabled:opacity-45 ${focus}`

export const moderatorShellUi = {
  app: 'flex min-h-[var(--screen-h,100dvh)] w-full bg-[#f0f4f8] font-sans text-[13px] text-[#16233a] [&_*]:box-border [&_button]:[-webkit-tap-highlight-color:transparent] [&_a]:[-webkit-tap-highlight-color:transparent] [&_button]:cursor-pointer [&_button:disabled]:cursor-not-allowed [&_button:disabled]:opacity-45',
  overlay: 'fixed inset-0 z-[59] hidden border-0 bg-[#0b193080] max-[900px]:block',
  sidebar: 'fixed left-0 top-0 z-[60] flex h-[var(--screen-h,100dvh)] w-[264px] -translate-x-full invisible flex-shrink-0 flex-col overflow-y-auto bg-[#0b1930] px-[16px] pb-[20px] pt-[30px] text-white transition-[transform,visibility] duration-200 min-[901px]:sticky min-[901px]:z-auto min-[901px]:translate-x-0 min-[901px]:visible max-[1200px]:w-[232px] max-[900px]:w-[264px]',
  sidebarOpen: 'max-[900px]:translate-x-0 max-[900px]:visible',
  sidebarExpanded: 'min-[901px]:w-[264px] max-[1200px]:min-[901px]:w-[232px]',
  sidebarCollapsed: 'min-[901px]:w-[76px] min-[901px]:px-[10px]',
  sidebarHeader: 'mb-[32px] flex items-center justify-between gap-[8px] min-[901px]:[&.is-collapsed]:flex-col min-[901px]:[&.is-collapsed]:gap-[12px]',
  brand: 'flex min-w-0 items-center gap-[12px] text-[23px] font-bold tracking-[-.7px] text-[#2e6db4] no-underline min-[901px]:[&.is-collapsed]:justify-center',
  brandMark: 'grid place-items-center rounded-[10px] bg-white p-[3px]',
  brandText: 'truncate min-[901px]:[&.is-collapsed]:hidden',
  collapseButton: `${icon} border-[#ffffff20] bg-[#ffffff09] text-[#a3b2c8] hover:bg-[#ffffff18] hover:text-white max-[900px]:hidden`,
  nav: 'flex min-h-0 flex-1 flex-col gap-[7px]',
  navItem: 'flex items-center gap-[12px] rounded-[8px] border-l-[3px] border-solid border-transparent px-[13px] py-[15px] text-[12px] font-semibold text-[#a3b2c8] no-underline transition-[background-color,color] duration-200 hover:bg-[#ffffff09] hover:text-white min-[901px]:[&.is-collapsed]:justify-center min-[901px]:[&.is-collapsed]:pr-[3px] min-[901px]:[&.is-collapsed]:pl-0',
  navActive: 'border-l-[#60a5fa] bg-[#ffffff14] text-white',
  navText: 'min-w-0 truncate min-[901px]:[&.is-collapsed]:hidden',
  navBadge: 'ml-auto rounded-[5px] bg-[#234269] px-[7px] py-[1px] text-[10px] text-[#c4dfff] min-[901px]:[&.is-collapsed]:hidden',
  user: 'mt-[24px] flex items-center gap-[10px] border-0 border-t border-solid border-[#ffffff16] px-[7px] pb-0 pt-[20px] min-[901px]:[&.is-collapsed]:flex-col min-[901px]:[&.is-collapsed]:px-0',
  avatar: 'grid h-[36px] w-[36px] shrink-0 place-items-center rounded-[9px] bg-[#285a9b] text-[12px] font-bold',
  userInfo: 'flex min-w-0 flex-1 items-center min-[901px]:[&.is-collapsed]:hidden',
  userName: 'block overflow-hidden text-ellipsis whitespace-nowrap text-[12px] leading-[1.2]',
  logout: `${icon} h-[34px] w-[34px] border-0 bg-transparent text-[#9bacc1] leading-none hover:bg-[#ffffff0c] hover:text-[#f87171]`,
  main: 'min-w-0 flex-1',
  header: 'flex min-h-[76px] items-center gap-[16px] border-0 border-b border-solid border-[#dce4ed] bg-[linear-gradient(90deg,#fff,#f8fafc)] px-[32px] py-[16px] max-[1200px]:px-[22px] max-[900px]:justify-start max-[600px]:min-h-[68px] max-[600px]:gap-[10px] max-[600px]:px-[16px] max-[600px]:py-[12px]',
  headerTitle: 'flex items-center gap-[12px] max-[900px]:gap-[8px]',
  headerIcon: 'rounded-[9px] bg-[#e6f0fa] p-[10px] text-[#1a528e] max-[600px]:p-[7px]',
  headerHeading: 'm-0 font-sans text-[15px] font-bold leading-[inherit] tracking-[.25px] text-[#16233a] uppercase max-[900px]:text-[13px]',
  headerDate: 'ml-auto flex items-center gap-[8px] text-[11px] text-[#64748b] max-[1200px]:text-[10px] max-[600px]:hidden',
  content: 'pb-[28px]',
  placeholder: 'grid min-h-[260px] place-items-center text-[15px] text-[#64748b]',
}
